---
- name: Update MongoDB Exporter Removal, Docker Installation, and Configuration
  hosts: mongodb_servers
  become: yes
  vars:
    mongodb_exporter_version: "0.40"  # Update to the latest version available
    mongodb_port: 27018
    mongodb_exporter_port: 9216
    monitoring_user: monitoringUser
    monitoring_password: "{{ mongodb_password | default(lookup('env', 'MONGODB_MONITORING_PASSWORD')) }}"
    mongodb_uri: "mongodb://{{ monitoring_user }}:{{ monitoring_password }}@localhost:27018"

  tasks:
    - name: Stop MongoDB exporter service if running
      systemd:
        name: mongodb_exporter
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove MongoDB exporter systemd service file
      file:
        path: /etc/systemd/system/mongodb_exporter.service
        state: absent
      ignore_errors: yes

    - name: Reload systemd after changes
      systemd:
        daemon_reload: yes
      ignore_errors: yes

    - name: Install Docker if not already installed
      block:
        - name: Install Docker prerequisites
          package:
            name: "{{ item }}"
            state: present
          with_items:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
          when: ansible_os_family == 'Debian'

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          when: ansible_os_family == 'Debian'

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
          when: ansible_os_family == 'Debian'

        - name: Update apt and install Docker
          apt:
            update_cache: yes
            name: docker-ce
            state: present
          when: ansible_os_family == 'Debian'

        - name: Install Docker on RedHat
          yum:
            name: docker
            state: present
          when: ansible_os_family == 'RedHat'

        - name: Ensure Docker service is started
          systemd:
            name: docker
            state: started
            enabled: yes

    - name: Pull the latest MongoDB exporter Docker image
      docker_image:
        name: percona/mongodb_exporter:{{ mongodb_exporter_version }}
        source: pull

    - name: Run MongoDB exporter container
      docker_container:
        name: percona_mongodb_exporter
        image: percona/mongodb_exporter:{{ mongodb_exporter_version }}
        ports:
          - "{{ mongodb_exporter_port }}:9216"
        environment:
          MONGODB_URI: "{{ mongodb_uri }}"
        state: started

    - name: Open firewall port for MongoDB exporter
      firewalld:
        port: "{{ mongodb_exporter_port }}/tcp"
        permanent: yes
        state: enabled
      notify:
        - Reload firewall

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Reload firewall
      command: firewall-cmd --reload
